// <auto-generated />
namespace FirstProject.BossContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddHist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHist));
        
        string IMigrationMetadata.Id
        {
            get { return "202102151112230_AddHist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
